### ISSUE TITLE
[p2p Code Review] Improvement to CSS #1 

### ISSUE THREAD

**Issue by Alondra87** [GiuseppeTG/Giuseppe-Concert-Webpage#4]
<h2>Hello @GiuseppeTG </h2>
Great work on your code👏
<h2>To highlight🎯</h2>
<ul>
<li>✔️ No linter errors</li>
<li>✔️ Good semantics HTML</li>
<li>✔️ Nice design</li>
</ul>
<img src="https://media2.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif"/>
<h2>Suggestions✍️</h2> 
We noticed there are height issue (100vh) in <code>.nav-menu</code> class affecting desktop version.

https://github.com/GiuseppeTG/Giuseppe-Concert-Webpage/blob/96966ff7542f3675cfc735590784eedba10e2694/styles.css#L567-L576

Kindly you could change inside the media query adding <code>height: max-content</code> to </code>.nav-menu class</code>.

You may also be interested in how to fix the effects of this (100vh) in some browsers like Safari in this link https://css-tricks.com/css-fix-for-100vh-in-mobile-webkit/

**Comment by GiuseppeTG** [comment]
Thank you so much for pointing out that problem!
I will work to improve it (:
